# Generated by Django 4.2.1 on 2023-06-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_cart_order_payment_reviews_store_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
