# Generated by Django 4.2.1 on 2023-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('order_items', models.TextField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_address', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
